### ISSUE TITLE
documentation on variables

### ISSUE THREAD

**Issue by bbaassssiiee** [hudecof/ansible_tomcat#1]
It took me a while to figure out the variables to set in my group_vars/environment,
I think tomcat_java_home is undocumented/undefined while a sensible default could be /usr/lib/jvm/jre

After setting that I managed to get it working by adding these to my group_vars:

   tomcat_download_prefix: "http://apache.cs.uu.nl/tomcat/tomcat-7/v7.0.59/bin/"
   tomcat_version: v7.0.59
   tomcat_list:
     v7.0.59:
       filename: 'apache-tomcat-7.0.59.tar.gz'
       dirname: 'apache-tomcat-7.0.59'
   tomcat_apps_dir: "/opt/{{ tomcat_list[tomcat_version]['dirname'] }}"

**Comment by hudecof** [comment]
my settings is like
```
# tomcat
tomcat_download_prefix: http://download.example.com/apache-tomcat
tomcat_list:
  v8.5.31:
    filename: 'apache-tomcat-8.5.31.tar.gz'
    dirname: 'apache-tomcat-8.5.31'
tomcat_version: v8.5.31
```
